/*
 * Copyright (c) 2010.
 * CC-by Felipe Micaroni Lalli <micaroni@gmail.com>
 * Special thanks to Igor Hjelmstrom Vinhas Ribeiro <igorhvr@iasylum.net>
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataInteger.proto

package br.eti.fml.stonerlmg.test;

public final class DataInteger {
  private DataInteger() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class DataIntegerMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use DataIntegerMessage.newBuilder() to construct.
    private DataIntegerMessage() {
      initFields();
    }
    private DataIntegerMessage(boolean noInit) {}
    
    private static final DataIntegerMessage defaultInstance;
    public static DataIntegerMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataIntegerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataInteger.internal_static_machineguntest_DataIntegerMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataInteger.internal_static_machineguntest_DataIntegerMessage_fieldAccessorTable;
    }
    
    // optional int32 onlyData = 1;
    public static final int ONLYDATA_FIELD_NUMBER = 1;
    private boolean hasOnlyData;
    private int onlyData_ = 0;
    public boolean hasOnlyData() { return hasOnlyData; }
    public int getOnlyData() { return onlyData_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasOnlyData()) {
        output.writeInt32(1, getOnlyData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasOnlyData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getOnlyData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static DataInteger.DataIntegerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DataInteger.DataIntegerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DataInteger.DataIntegerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DataInteger.DataIntegerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DataInteger.DataIntegerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DataInteger.DataIntegerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static DataInteger.DataIntegerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DataInteger.DataIntegerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DataInteger.DataIntegerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DataInteger.DataIntegerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DataInteger.DataIntegerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private DataInteger.DataIntegerMessage result;
      
      // Construct using DataInteger.DataIntegerMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new DataInteger.DataIntegerMessage();
        return builder;
      }
      
      protected DataInteger.DataIntegerMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new DataInteger.DataIntegerMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataInteger.DataIntegerMessage.getDescriptor();
      }
      
      public DataInteger.DataIntegerMessage getDefaultInstanceForType() {
        return DataInteger.DataIntegerMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public DataInteger.DataIntegerMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private DataInteger.DataIntegerMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public DataInteger.DataIntegerMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        DataInteger.DataIntegerMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataInteger.DataIntegerMessage) {
          return mergeFrom((DataInteger.DataIntegerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(DataInteger.DataIntegerMessage other) {
        if (other == DataInteger.DataIntegerMessage.getDefaultInstance()) return this;
        if (other.hasOnlyData()) {
          setOnlyData(other.getOnlyData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setOnlyData(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 onlyData = 1;
      public boolean hasOnlyData() {
        return result.hasOnlyData();
      }
      public int getOnlyData() {
        return result.getOnlyData();
      }
      public Builder setOnlyData(int value) {
        result.hasOnlyData = true;
        result.onlyData_ = value;
        return this;
      }
      public Builder clearOnlyData() {
        result.hasOnlyData = false;
        result.onlyData_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:machineguntest.DataIntegerMessage)
    }
    
    static {
      defaultInstance = new DataIntegerMessage(true);
      DataInteger.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:machineguntest.DataIntegerMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_machineguntest_DataIntegerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_machineguntest_DataIntegerMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DataInteger.proto\022\016machineguntest\"&\n\022D" +
      "ataIntegerMessage\022\020\n\010onlyData\030\001 \001(\005B)\n\032b" +
      "r.fml.eti.machinegun.testB\013DataInteger"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_machineguntest_DataIntegerMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_machineguntest_DataIntegerMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_machineguntest_DataIntegerMessage_descriptor,
              new java.lang.String[] { "OnlyData", },
              DataInteger.DataIntegerMessage.class,
              DataInteger.DataIntegerMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
